server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: alex
    url: jdbc:postgresql://localhost:5433/customer
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka